export const  SET_PENALTY_DATA = 'SET_PENALTY_DATA';
export const  SET_PENALTY_ERROR = 'SET_PENALTY_ERROR';
export const  CLEAR_PENALTY_ERROR = 'CLEAR_PENALTY_ERROR';
export const LOADING_PENALTY_DATA = 'LOADING_PENALTY_DATA';
export const  SET_PENALTY_MESSAGE = 'SET_PENALTY_MESSAGE';
export const  CLEAR_PENALTY_MESSAGE = 'CLEAR_PENALTY_MESSAGE';
