export const  SET_VEHICLE_DATA = 'SET_VEHICLE_DATA';
export const  SET_VEHICLE_PLATES_DATA = 'SET_VEHICLE_PLATES_DATA';
export const  SET_VEHICLE_ERROR = 'SET_VEHICLE_ERROR';
export const  CLEAR_VEHICLE_ERROR = 'CLEAR_VEHICLE_ERROR';
export const LOADING_VEHICLE_DATA = 'LOADING_VEHICLE_DATA';
export const  SET_VEHICLE_MESSAGE = 'SET_VEHICLE_MESSAGE';
export const  CLEAR_VEHICLE_MESSAGE = 'CLEAR_VEHICLE_MESSAGE';
