export const  SET_EXCEL_FILE_DATA = 'SET_EXCEL_FILE_DATA';
export const  SET_EXCEL_FILE_ERROR = 'SET_EXCEL_FILE_ERROR';
export const  CLEAR_EXCEL_FILE_ERROR = 'CLEAR_EXCEL_FILE_ERROR';
export const LOADING_EXCEL_FILE_DATA = 'LOADING_EXCEL_FILE_DATA';
export const  SET_EXCEL_FILE_MESSAGE = 'SET_EXCEL_FILE_MESSAGE';
export const  CLEAR_EXCEL_FILE_MESSAGE = 'CLEAR_EXCEL_FILE_MESSAGE';
