export const  SET_MENU_DATA_DATA = 'SET_MENU_DATA_DATA';
export const  SET_MENU_DATA_ERROR = 'SET_MENU_DATA_ERROR';
export const  CLEAR_MENU_DATA_ERROR = 'CLEAR_MENU_DATA_ERROR';
export const LOADING_MENU_DATA_DATA = 'LOADING_MENU_DATA_DATA';
export const  SET_MENU_DATA_MESSAGE = 'SET_MENU_DATA_MESSAGE';
export const  CLEAR_MENU_DATA_MESSAGE = 'CLEAR_MENU_DATA_MESSAGE';
