export const  SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const  SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const  SET_ERROR = 'SET_ERROR';
export const  CLEAR_ERROR = 'CLEAR_ERROR';
export const  SET_MESSAGE = 'SET_MESSAGE';
export const  CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const LOADING_USER = 'LOADING_USER';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
