
export const  SET_PDF_FILE_DATA = 'SET_PDF_FILE_DATA';
export const  SET_PDF_FILE_ERROR = 'SET_PDF_FILE_ERROR';
export const  CLEAR_PDF_FILE_ERROR = 'CLEAR_PDF_FILE_ERROR';
export const LOADING_PDF_FILE_DATA = 'LOADING_PDF_FILE_DATA';
export const  SET_PDF_FILE_MESSAGE = 'SET_PDF_FILE_MESSAGE';
export const  CLEAR_PDF_FILE_MESSAGE = 'CLEAR_PDF_FILE_MESSAGE';
