export const  SET_MENU_DATA = 'SET_MENU_DATA';
export const  SET_SINGLE_MENU_DATA = 'SET_SINGLE_MENU_DATA';
export const  SET_MENU_ENTRIES_DATA = 'SET_MENU_ENTRIES_DATA';
export const  SET_MENU_ERROR = 'SET_MENU_ERROR';
export const  CLEAR_MENU_ERROR = 'CLEAR_MENU_ERROR';
export const LOADING_MENU_DATA = 'LOADING_MENU_DATA';
export const  SET_MENU_MESSAGE = 'SET_MENU_MESSAGE';
export const  CLEAR_MENU_MESSAGE = 'CLEAR_MENU_MESSAGE';
