export const  SET_STATISTICS_DATA = 'SET_STATISTICS_DATA';
export const  SET_STATISTICS_ERROR = 'SET_STATISTICS_ERROR';
export const  CLEAR_STATISTICS_ERROR = 'CLEAR_STATISTICS_ERROR';
export const LOADING_STATISTICS_DATA = 'LOADING_STATISTICS_DATA';
